export const FORTUNE_INCREMENT = 'FORTUNE_INCREMENT';
export const FORTUNE_DECREMENT = 'FORTUNE_DECREMENT';
export const BLESSURE_DECREMENT = 'BLESSURE_DECREMENT';
export const BLESSURE_INCREMENT = 'BLESSURE_INCREMENT';
